### ISSUE TITLE
Tab completion in shells

### ISSUE THREAD

**Issue by JamiKettunen** [mindstorm38/portablemc#111]
[postmarketOS' pmbootstrap](https://gitlab.com/postmarketOS/pmbootstrap) has a good example of [Tab completion integration](https://wiki.postmarketos.org/wiki/Installing_pmbootstrap#Tab_completion) using [argcomplete](https://kislyuk.github.io/argcomplete/).

**Comment by mindstorm38** [comment]
I'm finally investigating this, after some time...

**Comment by mindstorm38** [comment]
argcomplete's default files completer is stupidly broken

**Comment by mindstorm38** [comment]
Ok, I'm trying to reinvent the wheel (writing my own completion scripts), but it's not that overkill in the end, imo. This also allows me to use standard Zsh completion function, this is definitely an improvement for things like files. Not yet worked on bash completion.

**Comment by mindstorm38** [comment]
I do not regret! I'm using the full power of Zsh completions and I can add suggestions that improves the standard help message.

![image](https://github.com/mindstorm38/portablemc/assets/17071361/e0864871-cfdb-4225-ae23-75d11809f448)

**Comment by mindstorm38** [comment]
Release 4.2.1, first support for autocompletion!
