### ISSUE TITLE
[Enhancement] Option to always use system provided java

### ISSUE THREAD

**Issue by JamiKettunen** [mindstorm38/portablemc#116]
As of #115 it will be possible for `portablemc` to use system provided java on systems where e.g. the glibc-linked binaries from Mojang won't work on a musl Linux system.

But this just got me thinking, why not provide the option to use system java as a flag/API feature on *any* system?

Here's how I imagine it working:
- `--use-system-java` will search for `java` (or on win32 `javaw` executable) in `PATH` and use it (similar to how it works currently on `musl` Linux systems, well since the upcoming version anyway)
  - maybe it would have to be `--use-system-java java` for example as I'm not sure if it's possible to make the flag optionally not take any value
- `--use-system-java /usr/lib/jvm/java-1.8-openjdk/jre/bin/java` would use this as the executable directly

Thoughts @mindstorm38?

**Comment by mindstorm38** [comment]
What will be different from the `--jvm` argument? Anyway it's a good idea but just making the value of `--jvm` optional would work (or special value that could not be confused with a file's path, like '/')

**Comment by JamiKettunen** [comment]
Oh right this was already implemented, sorry for the noise. `--jvm java` is good enough imo.

**Comment by mindstorm38** [comment]
> Oh right this was already implemented, sorry for the noise. `--jvm java` is good enough imo.

I hadn't even thought of that, but yes, this is enough IMO, and it also allows choosing version on linux like `java8`, `java17` and so on.
