### ISSUE TITLE
Game doesn't launch with fabric

### ISSUE THREAD

**Issue by SpectralArc** [mindstorm38/portablemc#120]
When I launch the game, I find everything working properly in the terminal. However, the game just crashes, and I can't really tell why. I attached my logs to the post.
Please help, thanks!
[latest.log](https://github.com/mindstorm38/portablemc/files/9997426/latest.log)

**Comment by SpectralArc** [comment]
After messing around with my mods folder, I found that the problem was the Essential mod. The game now launches however I would like to know whether you will fix this (if it is a problem with portablemc). Thanks!

**Comment by mindstorm38** [comment]
I was about to tell you to check your mods, but nice :)
