### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Vixeliz** [mindstorm38/portablemc#123]
I'm interested in using this launcher I've been looking for a simple cli launcher and this seems to be a nice option. However it doesn't seem to work on wayland. It fails to launch with the error that glfw doesn't support input focus.

**Comment by Vixeliz** [comment]
There is one other error that will occasionally happen can't tell what causes the different errors. But the other one is 
```
java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140087241203344
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:75)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:826)
	at efu.<init>(SourceFile:481)
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)
```

**Comment by Vixeliz** [comment]
I knew it was something weird my first thought was this i've setup linux so many times and never had this issue. It ended up being xwayland wasnt working despite being installed. Anyways this is solved and unrelated to portablemc my bad.

**Comment by Ristovski** [comment]
@Vixeliz Running Minecraft **_natively_** on Wayland requires an option to use the system glfw lib as opposed to the one from Minecraft (mentioned in #110) and a patched GLFW: https://github.com/Admicos/minecraft-wayland

By default, it will use xwayland to run on Wayland (xwayland being a compatibility layer to run Xorg only software on Wayland)
