### ISSUE TITLE
Stopped resolving loader for quilt out of nowhere

### ISSUE THREAD

**Issue by cunhar** [mindstorm38/portablemc#126]
```
$ python -m portablemc start --dry quilt:1.19.3
[  OK  ] Resolving quilt loader for 1.19.3...
[FAILED] Game version 1.19.3 not found.

```

nothing was changed recently in the system.  
ive trying reinstalling including deleting the .minecraft folder
ive also tried uninstalling python packages for portable and portable-quilt

**Comment by cunhar** [comment]
`$ python -m portablemc start --dry quilt:1.19.3:0.17.8
[  OK  ] Resolving quilt loader 0.17.8 for 1.19.3...
[FAILED] Loader version 0.17.8 not found.
`

**Comment by cunhar** [comment]
quit also works fine in the normal minecraft launcher

**Comment by cunhar** [comment]
![image](https://user-images.githubusercontent.com/1693935/210266527-0a7985b8-f2c2-4fbc-a699-fab26d0bf3a7.png)

**Comment by cunhar** [comment]
Could this be related to curseforge being down?

**Comment by mindstorm38** [comment]
We're using quilt.io API so I don't think, I check that this evening

**Comment by cunhar** [comment]
also getting a weird error when starting fabric... weird thing is that it does launch fine after

![image](https://user-images.githubusercontent.com/1693935/210269110-ec2d59d6-ae78-4441-ab31-aaeec555ee35.png)

**Comment by cunhar** [comment]
i also tried going to python 3.10 this morning and it also didnt work

**Comment by mindstorm38** [comment]
It's quite weird, I can access the API and it's version hasn't changed...

**Comment by Ristovski** [comment]
https://github.com/mindstorm38/portablemc/blob/bb10d7a0043185c2363c83103faf3cc75c72e641/src/quilt/portablemc_quilt/__init__.py#L142-L148

Could this be a generic network error? Perhaps a rate-limit? I suggest printing `err` in such cases, along with the raw status code returned, this might aid in debugging future failures.

**Comment by mindstorm38** [comment]
There already is a message when a network error happens, because it's not returned as a JsonRequestError and therefore not catched.

Here is the message with my network intentionally off:
![image](https://user-images.githubusercontent.com/17071361/212140243-f0a04ea9-5b7e-486b-b2bf-5f6fa8a7fa3b.png)

**Comment by mindstorm38** [comment]
Any update? So I can close the issue if fixed
