### ISSUE TITLE
Quilt has too many Parents

### ISSUE THREAD

**Issue by Eaterminer** [mindstorm38/portablemc#129]
At first I thought this was related to #126 but then I noticed the errors were different.
![image](https://user-images.githubusercontent.com/58890567/218202236-69f2e6bf-2b51-4ee0-ae33-373e39b8bdeb.png)

Python: 3.10.9
Portablemc: 3.2.1

Edit: Also happens on other versions of quilt, eg: 1.15 with quilt version 0.16.0

**Comment by Eaterminer** [comment]
There seems to be alot of issues with the quilt loader, interesting

**Comment by mindstorm38** [comment]
Oooo serious issue here

**Comment by mindstorm38** [comment]
@MisileLab 👀 I failed at reviewing ahah

**Comment by MisileLab** [comment]
hmm

**Comment by mindstorm38** [comment]
Should be resolved in new version of the add-on 1.0.1, I yanked the 1.0.0 one because this issue is really annoying.

https://pypi.org/manage/project/portablemc-quilt/release/1.0.1/
