### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by DevLimeAtSkyo** [mindstorm38/portablemc#130]
I can start the normal game using the api, so no command line just python but how would I exactly do this for Fabric?

**Comment by mindstorm38** [comment]
It's now possible using the fabric add-on. The latest versions introduced a super class of `Version`, called `FabricVersion` that you can use like here: https://github.com/mindstorm38/portablemc/blob/bef5a3d9b7623c31371d2f5e1c1da31509624d92/src/fabric/portablemc_fabric/__init__.py#L86-L123

Once you constructed an instance of this class with proper loader and/or game versions, you can use it as a regular `Version` instance.
