### ISSUE TITLE
KeyError: 'path' when running on MacOS

### ISSUE THREAD

**Issue by ItsNiceCraft** [mindstorm38/portablemc#136]
The following error is thrown every time the cli is run using the `portablemc` command:

```
[  OK  ] Resolved version 1.18.1.    
[  OK  ] Loaded version JAR.    
[  OK  ] Checked 3071 assets.
[  OK  ] Loaded logger.    
[      ] Loading libraries... Traceback (most recent call last):
  File "/Users/REDACTED/Desktop/REDACTED/dep/portablemc/__main__.py", line 23, in <module>
    portablemc.cli.main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/portablemc/cli.py", line 145, in main
    cmd(handler, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/portablemc/cli.py", line 350, in cmd
    handler(ns, new_context(ns))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/portablemc/cli.py", line 485, in cmd_start
    version.prepare_libraries(predicate=libraries_predicate)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/portablemc/__init__.py", line 456, in prepare_libraries
    lib_path = path.join(self.context.libraries_dir, lib_dl_meta["path"])
                                                     ~~~~~~~~~~~^^^^^^^^
KeyError: 'path'
```

MacOS Monterey, Python 3.11
Same code works fine on Windows

**Comment by ItsNiceCraft** [comment]
The command line is `python3 -m portablemc start -u someuser 1.18.1`
What exactly do you mean with the json file of that version? The one in .minecraft/versions?

**Comment by ItsNiceCraft** [comment]
If you're talking about the one in .minecraft/versions, https://pastes.dev/mqGUUzu2Rs

**Comment by mindstorm38** [comment]
Perfect! Might be an issue with OS rules

**Comment by mindstorm38** [comment]
From the pastebin I guess you've installed the version with another software, because it lacks the "path" key for every artifact. 

https://piston-meta.mojang.com/v1/packages/989549ecba162cba2ec066e19a2f0364586f18bf/1.18.1.json

**Comment by ItsNiceCraft** [comment]
Oh yeah, sorry, I think I launched vanilla 1.18.1 with the official minecraft launcher first. I can send over the 1.18.1.json generated by portablemc in a bit

**Comment by mindstorm38** [comment]
Ok, if you say that the launcher generated it, then portablemc should be compatible with it. Even if I find it weird that no path is being specified, because it's one of the few fields that cannot be removed, all others are possible to remove.

Btw when did you installed it? I would be surprised that the modern launcher discarded paths from the official metadata...

**Comment by ItsNiceCraft** [comment]
I'm not sure. Probably a few months ago
