### ISSUE TITLE
Printing issue with NoneType in downloading Fabric versions

### ISSUE THREAD

**Issue by matthewperiut** [mindstorm38/portablemc#14]
I'll give the full log, but it's on line 1471 of portablemc.py

C:\Users\Matthew\Documents>py portablemc.py start fabric:1.16.5
Addon 'Richer' requires module 'prompt_toolkit' to load. You can try to install it using 'pip install prompt_toolkit' or search for it on the web.
Resolving latest version of fabric loader for Minecraft 1.16.5...
=> The version is not cached, generating...
Resolving version 1.16.5
=> Found cached metadata, loading...
=> Version loaded.
=> Generated!
Resolving version fabric-1.16.5-0.11.3
=> Found cached metadata, loading...
=> Version loaded.
=> Parent version: 1.16.5
Resolving version 1.16.5
=> Found cached metadata, loading...
=> Version loaded.
Loading release fabric-1.16.5-0.11.3...
Loading jar file...
Downloading fabric-1.16.5-0.11.3.jar... 100.00%   36MB/s
Loading assets...
=> Verifying assets...
Loading logger config...
Loading libraries and natives...
Traceback (most recent call last):
  File "portablemc.py", line 1556, in <module>
    PortableMC().start(sys.argv[1:])
  File "portablemc.py", line 1108, in start
    exit(self.start_subcommand(subcommand, args))
  File "portablemc.py", line 1113, in start_subcommand
    return getattr(self, builtin_func_name)(args)
  File "portablemc.py", line 1351, in cmd_start
    runner=runner
  File "portablemc.py", line 494, in wrapper
    return func(old_func, *args, **kwargs)
  File "C:\Users\Matthew\Documents\MCC\standalone\addons\modloader_fabric\fabric.py", line 303, in game_start
    old(cmd_args=cmd_args, version=version, **kwargs)
  File "portablemc.py", line 1408, in game_start
    super().core_start(**kwargs)
  File "portablemc.py", line 258, in core_start
    classpath_libs, native_libs = self.core_ensure_libraries(version_meta)
  File "portablemc.py", line 452, in core_ensure_libraries
    self.download_file(DownloadEntry(lib_url, lib_path, name=lib_name))
  File "portablemc.py", line 1473, in download_file
    res = super().download_file(entry, start_size=start_size, total_size=total_size, progress_callback=progress_callback)
  File "portablemc.py", line 528, in download_file
    progress_callback(dl_size, entry.size, start_size, total_size)
  File "portablemc.py", line 1471, in progress_callback
    self.print("download.progress", entry.name, p_dl_size / p_size * 100, speed, of_total, end="")
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

**Comment by matthewperiut** [comment]
Oh, and an important note, I deleted .minecraft and it's causing a lot of problems haha

**Comment by mindstorm38** [comment]
I've found! I fix that

**Comment by mindstorm38** [comment]
Please test the fix in the [latest pre-release](https://github.com/mindstorm38/portablemc/releases/tag/v1.1.4-pre1).
Commentez ce problème s'il est résolu ou non.
