### ISSUE TITLE
Optifine installation

### ISSUE THREAD

**Issue by ZeralldMC** [mindstorm38/portablemc#145]
Hi. Question about the API. I saw a solution to the optifine problems in the issues, but didn't fully understand the implementation. I read several websites with instructions on how to install optifine manually and made sure that optifine doesn't need forge, right? So I installed myself `optipy` to get a link to the actual jar file of optifine for minecraft 1.18.1. One question - how to install it now having only a jar file?

I'm sorry if my question seemed silly. I just don't really feel like downloading forge or fabric for my launcher

My code:

```
def startGame():
    with open('app/config.json', 'r') as f:
        appConfig = json.load(f)
    main_dir = "app/user/data"
    work_dir = "app/user/minecraft"
    game_width = appConfig["game"]["width"]
    game_height = appConfig["game"]["height"]

    manifest = VersionManifest()
    ctx = Context(main_dir, work_dir)

    version_id, alias = manifest.filter_latest("1.18.1")
    version = Version(ctx, version_id)

    try:
        version.install()
        # Here, if not exception has been raised, the version is installed in directories 
        # specified by the context 'ctx'.
        # You can check if some files has failed to download, using the returned "dl_report",
        # which is of DownloadReport class (check sources).
    except VersionError as e:
        print(f"Version '{e.version}' not found.")
    except JvmLoadingError as e:
        print(f"No JVM found for you system.")

    eel.game_loader_end()

    start_opts = StartOptions()
    start_opts.disable_multiplayer = False
    start_opts.username = appConfig["accounts"]["currentPlayer"]
    start_opts.resolution = (game_width, game_height)

    start = Start(version)
    start.prepare(start_opts)
    start.start()
```

**Comment by mindstorm38** [comment]
It seems a bit complicated to install Optifine just from the downloaded JAR. Because it requires running it and getting the version's id. Imo i seems way simpler by using forge, but I must admit that the forge add-on is not currently production-ready...
