### ISSUE TITLE
Crashes when attempting to enter or create a world

### ISSUE THREAD

**Issue by Zabloing1** [mindstorm38/portablemc#147]
Portablemc will crash whenever I attempt to enter or create a world. 

If you need to know my os, it's a windows 10

**Comment by mindstorm38** [comment]
Is it Minecraft that is crashing, or the launcher itself?

**Comment by Zabloing1** [comment]
> Is it Minecraft that is crashing, or the launcher itself?

Its minecraft. It might be because I didn't include the user part of the command line

**Comment by mindstorm38** [comment]
Does it happen with official launcher? Also, if you have the crash log it can be helpful to send it here

**Comment by Zabloing1** [comment]
> Does it happen with official launcher? Also, if you have the crash log it can be helpful to send it here

I deleted the crash logs when I had to move my .minecraft folder.

**Comment by Zabloing1** [comment]
i attempted to do it. still crashes. it says that i didnt allocate enough heap to java when i did 
[hs_err_pid10740.log](https://github.com/mindstorm38/portablemc/files/11642928/hs_err_pid10740.log)

**Comment by mindstorm38** [comment]
It makes no sense to me, I'll try to reproduce, and if I get lucky it'll be easier
