### ISSUE TITLE
download Java automatically

### ISSUE THREAD

**Issue by tarneaux** [mindstorm38/portablemc#15]
Hi,
This is not quite an issue, but I'd like to know how you achieved to download the latest Java. I'm making a project for a Minecraft / Discord communication, so if you could help me, it'd be great!
Thanks!

**Comment by mindstorm38** [comment]
Hi, if you are talking about version downloaded automatically by the official Mojang launcher, check the following link : https://launchermeta.mojang.com/v1/products/java-runtime/2ec0cc96c44e5a76b9c8b7c39df7210883d12871/all.json

**Comment by tarneaux** [comment]
Thanks, that's really helpful for my project!

**Comment by mindstorm38** [comment]
I close this issue but you can comment it and I will re-open it.
