### ISSUE TITLE
Fabric Loader no longer auto connecting to server with --server

### ISSUE THREAD

**Issue by cunhar** [mindstorm38/portablemc#153]
python -m portablemc start fabric:1.20.1 --resol 1920x1080 --server mc.hoobs.live -m -l xxxx@hotmail.com

```
[  OK  ] Resolving fabric loader for 1.20.1...
[  OK  ] Resolved version fabric-1.20.1-0.14.21.
[  OK  ] Loaded version JAR.
[  OK  ] Checked 3583 assets.
[  OK  ] Loaded pretty logger.
[  OK  ] Loaded 76 libraries.
[  OK  ] Loaded Mojang Java 17.0.3.
[  OK  ] Session validated for cunhar@gmail.com.
[  OK  ] Username: HoobsLive (xxxx)

```

This no longer auto connects me to the server and it just its in the main screen.  Ive also tested with no mods intalled.

**Comment by cunhar** [comment]
seems that multimc did some updates around that in its last update as lauchign the game with multimc works fine:

ref: https://github.com/MultiMC/Launcher/commit/71cf4f8d18a9ed2c1e67f25fcdd32d49c2ecf074

**Comment by mindstorm38** [comment]
It seems related to the latest "quickPlay" arguments they added, which removed the older ones (weird imo). I'll fix that for v4

**Comment by cunhar** [comment]
thanks for the quick aknowledgement <3

**Comment by mindstorm38** [comment]
Now working with retro-compatiblity with older versions that were using `--server` and `--port` arguments. The API now supports all quick play types (multiplayer, singleplayer and realms). Only multiplayer is support by the CLI for now, not planned for first releases of v4.
