### ISSUE TITLE
Multiplayer disabled for no-premium (unregistered) users (1.16.4 & 1.16.5)

### ISSUE THREAD

**Issue by unaiiglesias** [mindstorm38/portablemc#154]
For some reason, the versions 1.16.4 and 1.16.5, when run in offline mode, have the multiplayer mode disabled.
If you login in with Microsoft and re-open the game it works. This only seems to happen in those specific versions and happens both when the gme is launched via CLI and via API (In case that matters).
OS: Windows 10 64 bits
PMC version: 3.3.1
Python version: 3.10.4

![image](https://github.com/mindstorm38/portablemc/assets/103540554/382c5b44-487f-43bf-8450-5ead180349ef)

**Comment by Ristovski** [comment]
Changelog for reference: https://breezewiki.pussthecat.org/minecraft/wiki/Java_Edition_1.16.4

This is the version which adds some of the "Social interactions" settings, I assume this might be relevant somehow.

**Comment by mindstorm38** [comment]
Never seen that, I hope that offline mode is not broken after these versions...

**Comment by unaiiglesias** [comment]
Its not, from 1.17 on it works perfectly fine.

**Comment by Ristovski** [comment]
It indeed appears that only those two versions are affected.

I don't have the time right now but one could clone https://github.com/FabricMC/yarn/ twice - once the branch `1.16.4` and then the branch `1.17`.

Then in each run `./gradlew decompileCFR`. This will decompile both versions and produce deobfuscated source code which can be diffed.

I suggest looking at `public boolean isMultiplayerEnabled()` and the checks it does.

**Comment by mindstorm38** [comment]
```java
private final SocialInteractionsService field_26902;
public boolean isMultiplayerEnabled() {
    return this.multiplayerEnabled && this.field_26902.serversAllowed();
}
```

This looks good. What I find weird is the authlib version used only by 1.16.4 and 1.16.5: authlib v2.1.28

This may be the issue here

**Comment by mindstorm38** [comment]
I created a custom 1.16.5 version with authlib:2.2.30 and it fixes the problem!

**Comment by mindstorm38** [comment]
I'm no longer able to reproduce nooooooooooo

**Comment by mindstorm38** [comment]
To check when v4 pre-release will be out
