### ISSUE TITLE
Compact portablemc.exe

### ISSUE THREAD

**Issue by Siqust** [mindstorm38/portablemc#157]
I'm trying to create launcher to play with my friends. They probably don't have python (and portablemc so i need somehow launch portablemc from files they can download to any folder)   I have tried to convert portablemc to exe (with pyinstaller) (combined forge's __init__.py and core __init__.py). But it doesn't see forge addon.
Also it would be great if you can show me documentation use of portablemc in python(not in cmd)

**Comment by mindstorm38** [comment]
Hi, honestly I don't know how pyinstaller works, could you specify all packages to include in the executable? If so you can include portablemc and portablemc-forge and PMC should be able to discover the add-on, if not it's a bug in the launcher...

For the API documentation, it's not going to be upgraded for the current version (v3) but upcoming v4 is going to have a new updated documentation, so one thing I would suggest is to wait for v4 pre-release (planned for this weekend). In bonus, forge/fabric support will be included in the core package!

Also, thank you for considering PortableMC for your launcher!

**Comment by Siqust** [comment]
Thank you for your response. I thought pyinstaller includes main file and everything that it imports. For example if main file imports some module, pyinstaller combines module and main file. But I tried to import portable-mc forge into core file and it output error. Anyways thank you for information about fourth version, I will wait for it.

**Comment by mindstorm38** [comment]
Here's the post about first pre-release: https://github.com/mindstorm38/portablemc/issues/146#issuecomment-1656874939

**Comment by Siqust** [comment]
Portable mc can now be used as in-python utility
