### ISSUE TITLE
skin support for offline mode

### ISSUE THREAD

**Issue by dan-the-fan** [mindstorm38/portablemc#158]
it would be pretty cool to have skin support for offline mode somehow

**Comment by Ristovski** [comment]
I don't think this is possible without either patching the default resource pack (to replace the default skin image), or modding Minecraft itself, both of which I assume are out-of-scope for this launcher.

If you are running a dedicated offline-mode server, there exist mods/plugins such as https://modrinth.com/mod/fabrictailor

**Comment by mindstorm38** [comment]
Thank you, @Ristovski, for handling this case! 

As he said, this would be a bit out-of-scope for the launcher to modify the default resource pack... But, if you don't know, you already trick the game by specifying a UUID of an already existing skin, you can still pick any username. I don't know the limits of this technique, but it exists!
