### ISSUE TITLE
Ram usage minecraft portablemc 4.0.0rc1 (in python)

### ISSUE THREAD

**Issue by Siqust** [mindstorm38/portablemc#160]
How can I change minecraft ram usage in python? I tried to find it in api (https://github.com/mindstorm38/portablemc/blob/v4-rc/doc/API.md), but sadly didn't found it

**Comment by Siqust** [comment]
![image](https://github.com/mindstorm38/portablemc/assets/104167108/0ca2cf83-a27a-4089-a6a5-604e8b01e729)

**Comment by Siqust** [comment]
I found 
![image](https://github.com/mindstorm38/portablemc/assets/104167108/69b0fa9a-eb03-4ee1-a888-ce8bebc7588e)
And tried to write
version = ForgeVersion("1.19.2-43.2.21",context=Context(Path('.\\'),Path('.\\')))
version.set_auth_offline(username,'123')
version.jvm_path = f'-Xmx{ram}G'
version.install().run()
but gon an error: (without version.jvm_path is okay)

Traceback (most recent call last):
  File "F:\.minecrafts\new_server_with_launcher\launch\core_launch.py", line 85, in <module>
    raise e
  File "F:\.minecrafts\new_server_with_launcher\launch\core_launch.py", line 82, in <module>
    version.install().run()
  File "F:\py\lib\site-packages\portablemc\standard.py", line 183, in run
    (runner or StandardRunner()).run(self)
  File "F:\py\lib\site-packages\portablemc\standard.py", line 1505, in run
    process = self.process_create([
  File "F:\py\lib\site-packages\portablemc\standard.py", line 1523, in process_create
    return Popen(args, cwd=work_dir)
  File "F:\py\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\py\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]

**Comment by mindstorm38** [comment]
The `jvm_path` can only be set to the actual jvm executable (java and javaw on windows). For JVM arguments, you should use `jvm_args` on the `Environment` instance returned by the `install` function:

```python
version = Version(...)
env = version.install()
env.jvm_args.append(f"-Xmx{ram}G")
env.run()
```

I'll document this!

**Comment by Siqust** [comment]
Thank you! It helped

**Comment by mindstorm38** [comment]
Documented here: https://github.com/mindstorm38/portablemc/blob/v4-rc/doc/API.md#environment

**Comment by viper968** [comment]
do you mind updating how to change the RAM usage considering that doc link no longer functions nor does the section of code seem to exist anymore in the current version of the code?

**Comment by Ristovski** [comment]
@viper968 https://github.com/mindstorm38/portablemc/blob/main/doc/API.md#environment

Should work the same as the given code snippet

**Comment by viper968** [comment]
thank you
