### ISSUE TITLE
Server autojoin not working

### ISSUE THREAD

**Issue by HURDOO** [mindstorm38/portablemc#162]
![image](https://github.com/mindstorm38/portablemc/assets/64835865/b5280c30-b79a-465a-8e7f-cd36bdb813e9)
It does not join the provided server after launch automatically
(I know hypixel is online server, but also offline-mode server acts the same)

**Comment by mindstorm38** [comment]
What PMC version are you running? Also, it appears that you are using offline username, so this wouldn't work for connecting to hypixel.

**Comment by mindstorm38** [comment]
Could you try using the latest pre-release 4.0.0rc3, if you are already I'll investigate.

**Comment by mindstorm38** [comment]
Please test the latest release 4.0.0, it implements a fix for this issue.
