### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by elmundomusical4** [mindstorm38/portablemc#163]
Hi! I need to add the launcher in a usb, so it have to be portable. How can I do it?
So much thanks for this incredible project!

**Comment by Ristovski** [comment]
Sort-of-duplicate of https://github.com/mindstorm38/portablemc/issues/157, according to that issue you can use `pyinstaller` to convert the script to a single .exe which bundles Python inside it (this will likely result in a big file). I doubt that it will work perfectly out of the box however.
