### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by JXSnack** [mindstorm38/portablemc#169]
I have a few questions.
- How do I start the game with mods
- Where do I find the game logs

I am sorry if these questions are kinda dumb, but I checked the docs and couldn't find anything.

**Comment by mindstorm38** [comment]
To start with mods, you just have to start a mod loader of your choice, like fabric or forge (this part is documented), but it's your responsibility to put the mods you want in the `mods` directory.

For the logs, and I think this part is not documented yet, you can specify a custom runner when calling `.run(...)` function. For your custom runner you can just subclass the `StreamRunner` class, it provides abstract functions that you can redefine, these functions are called when new log lines are pushed by the game. I'll document this soon, if you are okay waiting for it.

**Comment by JXSnack** [comment]
Thank you! Is it possible to change the directory from .minecraft to something else? Or does it always have to be .minecraft

**Comment by JXSnack** [comment]
figured it out with context
