### ISSUE TITLE
Support automatic mod download from Modrinth

### ISSUE THREAD

**Issue by Ristovski** [mindstorm38/portablemc#17]
Modrinth seems to be the sanest modding platform, which also provides a _very_ convenient API: https://github.com/modrinth/labrinth/wiki/Examples.

Even though not many mods are on Modrinth as of now, most of the "standard" and well-known (not to mention - well-made :P) Fabric mods (such as Sodium etc) are, so supporting this is is worth looking into imo.

**Comment by mindstorm38** [comment]
Really good idea! I failed to make an automatic mod downloader for now because I was stuck with cursemc, but with this it seems way easier.

**Comment by mindstorm38** [comment]
Working on it by the way!

**Comment by mindstorm38** [comment]
Do not hesitate to write feedbacks here, I really want to improve the addon and make it really handy in the CLI before actually releasing it officially.

**Comment by mindstorm38** [comment]
I'll improve the add-on soon :)

**Comment by mindstorm38** [comment]
I dropped the wip "modrinth" add-on in the latest launcher version because I found a dedicated alternative to this topic: Feriu
