### ISSUE TITLE
Question about API authentication

### ISSUE THREAD

**Issue by JXSnack** [mindstorm38/portablemc#172]
As I have not found any other place to ask this, I will ask this here.

I have searched in the documentation but I could not find an answer on how to authenticate the user in a script (so not the command line). My current code looks like this:
```python
context = Context(Path(os.getcwd() + "/minecraft_data"), Path(os.getcwd() + "/minecraft"))  # set custom folder, so we don't overwrite other important files
version = Version("release", context=context)  # set the latest version, and run in custom folder
version.install().run()  # Finally, run.
```

and it runs offline mode minecraft which makes sense as I haven't given any credentials. Now, running the same thing on the command line *with* the account looks something like this
```
portablemc start release --auth-anonymize -l foo@spam.com
```
We basically say start the latest version and run it on the email `foo@spam.com`. Running this for the first time will result in a webpage from Microsoft being opened, which makes it easy to integrate online support. I wanted to also do this in the script, so I changed my code to this
```python
context = Context(Path(os.getcwd() + "/minecraft_data"), Path(os.getcwd() + "/minecraft"))
version = Version("release", context=context)
version.auth_session = # and then I got stuck here
version.install().run()
```
but I got stuck at the `version.auth_session = `, because I didn't really understand how to start it like that. Maybe this question is a bit weird, but how do I log into the account with a script instead of the command line?

**Comment by mindstorm38** [comment]
Sorry, I didn't have time to finish the documentation last evening, I'll finish it this evening. Also, I think your understandings are good!

> Even if I click on the link it instantly goes to the redirect_uri, so I think I misunderstood something, as there is no Microsoft account with the email foo@spam.com.

I already encountered this kind of issue, it sometime happens with their login page when you're already connected with an account. I don't really know how to reproduce this, maybe using `MicrosoftAuthSession.get_logout_url` and following the link (this will be documented).

**Comment by JXSnack** [comment]
Sadly even with the logout url it still does not work.

> Sorry, I didn't have time to finish the documentation last evening, I'll finish it this evening. Also, I think your understandings are good!

When do you think it will be documented?

**Comment by mindstorm38** [comment]
This evening

**Comment by JXSnack** [comment]
Hey, sorry for asking all the time, but did you forget to push the commit? I still can't find a documentation on it.

**Comment by mindstorm38** [comment]
@JXSnack Available in latest commit!

**Comment by creeper-0910** [comment]
Sorry for the sudden question.
What value can be entered for client_id?

**Comment by mindstorm38** [comment]
Client ID is usually an identification string that should be unique to the client making requests to the API. It can be kept the same for the whole life of your launcher and for all requests, for any email.

The identification is usually a UUID *(without hyphens if I remember)*, at least I'm using this for the launcher's CLI.

**Comment by creeper-0910** [comment]
Thank you very much!

**Comment by creeper-0910** [comment]
After logging into my Microsoft account, I wrote the following code to save my credentials and use them the next time I log in, but it did not work correctly due to "portablemc.auth.OutdatedTokenError". OutdatedTokenError".
Is there any way to fix it?
```
if not os.path.isfile(Path.cwd() / 'auth.json'):
            if MicrosoftAuthSession.check_token_id(server.ms_auth_id_token, email, nonce):
                version.auth_session = MicrosoftAuthSession.authenticate(client_id, app_id, server.ms_auth_code, code_redirect_uri)
                authdata = {'id' : client_id,'token': server.ms_auth_id_token, 'email' : email, 'code' : server.ms_auth_code, 'nonce' : nonce}
                with open(Path.cwd() / 'auth.json', 'w') as f:
                    json.dump(authdata, f, ensure_ascii=False, indent=4)
else:
            with open(Path.cwd() / 'auth.json') as f:
                    cache = json.load(f)
            if MicrosoftAuthSession.check_token_id(cache["token"], cache["email"], cache['nonce']):
                version.auth_session = MicrosoftAuthSession.authenticate(cache["id"], app_id, cache["code"], code_redirect_uri)
                print(version.auth_session.username)
            else:
                print("autherror")
```
