### ISSUE TITLE
Neoforged repo for ForgeVersion

### ISSUE THREAD

**Issue by MisileLab** [mindstorm38/portablemc#180]
https://neoforged.net
It maybe works with existing forge.py

**Comment by mindstorm38** [comment]
I'll take a look at it soon!

**Comment by mindstorm38** [comment]
The installer seems compatible.

**Comment by mindstorm38** [comment]
Note for me:
Installers Maven URL: https://maven.neoforged.net/#/releases/net/neoforged/forge
All version can be fetched from https://maven.neoforged.net/releases/net/neoforged/forge/maven-metadata.xml

Their maven repo have API for querying a specific version: https://maven.neoforged.net/api/maven/latest/version/releases/net%2Fneoforged%2Fforge?filter=1.20.1

**Comment by mindstorm38** [comment]
I don't know if the original Minecraft Forge project will continue releasing for long, but for now both supports 1.20.1. I would like to support both in the current `ForgeVersion` API, to do so I can fallback to neoforge maven if original maven don't have the request version, therefore the launcher would not need an update in the future if original forge is discontinued. I also want users of the API to be able to select which version if they wish, in the CLI this could be a `--forge-upstream {original,neoforged}`.

**Comment by mindstorm38** [comment]
![image](https://github.com/mindstorm38/portablemc/assets/17071361/1db31c46-c5b9-4e3f-9fbb-3be712d4fc74)
ouch

**Comment by mindstorm38** [comment]
Ok, User-Agent seems enough

**Comment by mindstorm38** [comment]
It's working!

**Comment by mindstorm38** [comment]
@MisileLab Available in latest version 4.1.0! Please give feedback, it works on my systems at least, so I hope it will work for you.
