### ISSUE TITLE
Invalid session

### ISSUE THREAD

**Issue by superniels09** [mindstorm38/portablemc#182]
I logged into portablemc with 
portablemc login [my e-mail] 
and started 1.8.9 using 
portablemc start 1.8.9
the game worked completly fine but when trying to get into hypixel it said "invalid session try restarting your game"

how do I fix this?

**Comment by mindstorm38** [comment]
Using `portablemc login` alone is not sufficient, you also need to add `-l <email>` in the start command line: `portablemc start -l you@example.com 1.8.9`

**Comment by mindstorm38** [comment]
A little tip has been added in latest version 4.1.0
