### ISSUE TITLE
Installing mods with events

### ISSUE THREAD

**Issue by ZeralldMC** [mindstorm38/portablemc#186]
Good night, I'm trying to figure out eventing. I need to have several mods added to the mods folder at full load of minecraft. I have a script that allows you to do this, but it must be run after the full installation of the game itself. 

My current code:

```
    class MyWatcher(Watcher):
        def handle(self, event) -> None:
            print(f"Event activated: {event}")
            if isinstance(event, DownloadCompleteEvent):
                print("Minecraft downloaded")
                modsCheck()

    try:
        env = version.install(watcher=MyWatcher())
        env.run()
    finally:
        eel.game_loader_end()
```

How can I do this and am I even moving correctly? I'm afraid I've misunderstood something.

**Comment by mindstorm38** [comment]
You don't need event watcher for that use case! You can just check your mods between the `.install(...)` and `.run()`.
Events are usually for debugging or printing progress to the client, not really for updating the game's state, but that's still possible if you wish!
