### ISSUE TITLE
Possible to add info to README re: another method of contributing...?

### ISSUE THREAD

**Issue by user10072023github** [mindstorm38/portablemc#187]
Wondering if you have Kofi/Patreon to show my gratitude...really dislike M$ so "GitHub Sponsors" is deservedly or undeservedly lumped into that general category...
Thanks again

**Comment by mindstorm38** [comment]
Thank you so much! I didn't expect to receive this much attention, so I didn't care about Kofi/Patreon until now. I'll let you know as soon as I create a page!

**Comment by mindstorm38** [comment]
I'm back with a ko-fi account! https://ko-fi.com/theorozier
I'll add it to the FUNDING.yml of the repo for the next release.

**Comment by user10072023github** [comment]
Excellent, heading there now!  Thanks again for the great project!

**Comment by mindstorm38** [comment]
Thank you so much for the support!
