### ISSUE TITLE
portablemc start forge:1.20.1-latest does not work

### ISSUE THREAD

**Issue by MisileLab** [mindstorm38/portablemc#189]
Log:
```
[FAILED] Version forge-1.20.1-??? not found
```

**Comment by mindstorm38** [comment]
Should be how it works, hope it's not new issue with neoforge

**Comment by mindstorm38** [comment]
Ok I think that I understand, you start with `forge:1.20.1-latest`? If this is the case, just use `forge:1.20.1` instead, it uses recommended and then latest as fallback, should be what you need?

**Comment by MisileLab** [comment]
I want latest at first and recommend as fallback

**Comment by mindstorm38** [comment]
So are you suggesting inverting the default fallback order or just be less strict about -latest and -recommended when one is not available? (I prefer the last latter)

**Comment by MisileLab** [comment]
I prefer last one(just give warning when not avaliable and fallback)

**Comment by mindstorm38** [comment]
Looks good to me, I'll work on that.

**Comment by mindstorm38** [comment]
Implemented in next release!

**Comment by mindstorm38** [comment]
Release 4.2.1, implemented this fallback
