### ISSUE TITLE
Missing minecraft resource

### ISSUE THREAD

**Issue by elmundomusical4** [mindstorm38/portablemc#192]
Hi! I'm getting this error when I run forge 1.16.5. How can I fix it?
`print:[13:25:03] [main] [INFO] ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_51 by Oracle Corporation\n
print:[13:25:03] [main] [WARN] LEGACY JDK DETECTED\, SECURED JAR HANDLING DISABLED\n
print:[13:25:03] [main] [INFO] Added Lets Encrypt root certificates as additional trust\n
print:[13:25:03] [main] [INFO] SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Javier%20Ben%c3%adtez/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT\n
print:[13:25:04] [main] [FATAL] Failed to find Minecraft resource version 1.16.5-20210115.111550 at C:\Users\Javier Benítez\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.16.5-36.2.34\forge-1.16.5-36.2.34-client.jar\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler$$Lambda$183/1222768327.accept(Unknown Source)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:202)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$107/1278254413.accept(Unknown Source)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)\n
print:[13:25:04] [main] [INFO] [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)\n
`
Thanks!

**Comment by elmundomusical4** [comment]
I fix it deleting the forge libraries folder under .minecraft

**Comment by mindstorm38** [comment]
This is still an issue on my side, I really need to make more validation because most users are going to think that it's inherently a launcher issue.

**Comment by mindstorm38** [comment]
No problem, I just need to check that all libraries are existing, it's annoying tho because it's redundant with the common code.
