### ISSUE TITLE
Issue login with Microsoft auth

### ISSUE THREAD

**Issue by Gustoon** [mindstorm38/portablemc#199]
When I try to connect with Microsoft, and I fill out everything on the web page, the terminal gets stuck at one step:
`[ .. ] Opened authentication page in browser...`
and it does not ask me for the code displayed on the internet page.
What to do?

**Comment by Gustoon** [comment]
Yes, I am redirected to this site once logged in. On this page, it is written:
Forwarding request to your local launcher (port 62772)
No local launcher detected, if requested you can copy the following code:
*A code*

**Comment by mindstorm38** [comment]
Ok, this is weird. Do you see anything weird on your web browser network view? In particular the reason for why the request doesn't succeed. Anyway, I think you could temporarily fix the problem by using `--auth-no-browser`, but you'll have to manually enter URL and code. If you have some time I would like to fix the issue (if on my side)..

**Comment by Gustoon** [comment]
I just checked in "inspect -> network" and there is an error "?id_token=...".
And --auth-no-browser also gives me an error even though I have a Minecraft account.

**Comment by mindstorm38** [comment]
Without giving us any personal info, could you be more precise about the error with the request to localhost? I'm afraid there are some kind of cross site issue...

**Comment by Gustoon** [comment]
yes I want to but how?

**Comment by mindstorm38** [comment]
![image](https://github.com/mindstorm38/portablemc/assets/17071361/11a41ec9-4324-4b02-955a-994650694dfc)
With something like this

**Comment by mindstorm38** [comment]
Ok so the request is blocked by your browser, as I expected. Is there any error message in the "console" tab related to blocked request ?

**Comment by Gustoon** [comment]
I have this error : net::ERR_BLOCKED_BY_CLIENT

**Comment by mindstorm38** [comment]
What is the error when you use no-browser option ?

**Comment by Gustoon** [comment]
When I paste the code and press "Enter", I get this error:
`[FAILED] Error authenticating:`

**Comment by mindstorm38** [comment]
Everything works on my side, I don't understand, at least no-browser should work

**Comment by Gustoon** [comment]
i using brave

**Comment by mindstorm38** [comment]
Interesting, so there is still an issue with authentication itself... This is way harder to debug however.

**Comment by Gustoon** [comment]
Yes surely

**Comment by Gustoon** [comment]
Yes i have the correct account. Do I need to do an update to obtain these new messages?

**Comment by mindstorm38** [comment]
I've modified the launcher to be more explicit about outdated token/game not owned in the latest v4.3 branch, but this is not yet released. You can try it, I hope with `pip -v install --upgrade --force-reinstall "git+https://github.com/mindstorm38/portablemc.git@v4.3"` (seems to require git to be installed).

**Comment by Gustoon** [comment]
It tells me: "Error authenticating: does not own minecraft" while on minecraft.net it tells me that I own minecraft.

**Comment by Gustoon** [comment]
Ok.

**Comment by Gustoon** [comment]
I redid the update
`pip -v install --upgrade --force-reinstall "git+https://github.com/mindstorm38/portablemc.git@v4.3"`
and now its march!
I really don't know why.

**Comment by Gustoon** [comment]
Now maybe you can implement this update on the github repository?

**Comment by mindstorm38** [comment]
Yes I'll keep this, maybe with better diagnostics.

**Comment by Gustoon** [comment]
You can also add text on the redirect page that says to deactivate the ad blocker because when I had an ad blocker, it worked even less!

**Comment by Gustoon** [comment]
ok, can i close the issue?

**Comment by mindstorm38** [comment]
I guess so

**Comment by mindstorm38** [comment]
![image](https://github.com/mindstorm38/portablemc/assets/17071361/12b5a05b-469c-46bb-85a7-a40ab4ee1bef)
When I said that the CI is blocked... lmao
