### ISSUE TITLE
error: unrecognized arguments: --work-dir fabric:1.20.1

### ISSUE THREAD

**Issue by Xanderplayz16** [mindstorm38/portablemc#203]
I am trying to launch the game, but it returns an error. How do I fix this?
CMD: 
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\xande> python -m portablemc start -u aaa --work-dir X:\Desktop\supahlaunchah\splauncher\instances\aaa fabric:1.20.1
usage: portablemc [-h] [--main-dir MAIN_DIR] [--work-dir WORK_DIR] [--timeout TIMEOUT]
                  [--output {human-color,human,machine}] [-v]
                  {search,start,login,logout,show} ...
portablemc: error: unrecognized arguments: --work-dir fabric:1.20.1
PS C:\Users\xande>
```

**Comment by Ristovski** [comment]
`--work-dir` is a global argument and needs to come _before_ `start` as per the first line of https://github.com/mindstorm38/portablemc?tab=readme-ov-file#commands. Likewise, `-u` is an arg and needs to come _after_ the `start` command.

The correct command would be `python -m portablemc --work-dir X:\Desktop\supahlaunchah\splauncher\instances\aaa start fabric:1.20.1 -u aaa`

**Comment by Xanderplayz16** [comment]
Ohhhhh
Thanks
