### ISSUE TITLE
Version Install Hanging

### ISSUE THREAD

**Issue by Trogiken** [mindstorm38/portablemc#226]
As described in the API documentation, I configure the version:
```python
from portablemc.standard import Version, Context

context = Context(<Pathlib.Path>, <Pathlib.Path>)  # Example
version = Version("1.20.6", context=context)

version.install()  # A watcher is provided here but too large for a example
```

Rearing the end of the installation process, the download/thread activity stops with no clear sign of why.
The "solution" I've been using is to crash the install via the watcher when the last download entry name is seen `<DownloadEntry modules>` (This name is seemingly version specific), then start the install again, it picks up where it got seemingly stuck, and finishes the install, sending a `DownloadCompleteEvent`. This solution was only a bandaid and no longer feasible for me now.

I've been stumbling around this issue for a couple days and now looking for guidance.

I know you're busy working on the rust rewrite but any help is greatly appreciated.

**Comment by Trogiken** [comment]
Here is the file in question: https://github.com/Trogiken/Hominum-Updater/blob/staging/Updater/source/mc/minecraft.py

The method in question is `MCManager.provision_environment()`

**Comment by Trogiken** [comment]
After taking the raw components and running them separately, this problem doesn't seem to be related to portablemc.

**Comment by mindstorm38** [comment]
No problem, thank you for using PMC :)

> I know you're busy working on the rust rewrite but any help is greatly appreciated.
I'm still actively maintaining the Python version, even if it takes more time now!

**Comment by Trogiken** [comment]
That's great to hear, good luck with rust.
