### ISSUE TITLE
Neoforge out of Beta

### ISSUE THREAD

**Issue by Trogiken** [mindstorm38/portablemc#228]
Neoforge as seen [here](https://projects.neoforged.net/neoforged/neoforge) is now out of beta.

With this new event do you think PMC can provide better versioning support for the new loader?

I could be wrongly inputting the loader version, below is an example of what I've tried:

```python
from portablemc.forge import _NeoForgeVersion

version = _NeoForgeVersion("1.20.6-21.0.143")
version.install()
```

This is the error output:

```
Traceback (most recent call last):
  File "c:\Users\Owner\VScode\Hominum-Launcher\tmp.py", line 4, in <module> 
    version.install()
  File "C:\Users\Owner\VScode\Hominum-Launcher\.venv\lib\site-packages\portablemc\standard.py", line 319, in install
    self._resolve_metadata(watcher)
  File "C:\Users\Owner\VScode\Hominum-Launcher\.venv\lib\site-packages\portablemc\standard.py", line 360, in _resolve_metadata
    self._fetch_version(handle, watcher)
  File "C:\Users\Owner\VScode\Hominum-Launcher\.venv\lib\site-packages\portablemc\forge.py", line 141, in _fetch_version
    raise VersionNotFoundError(version.id)
```

**Comment by mindstorm38** [comment]
I thought I already fixed the problem in the latest version (#223), I'll investigate, thank you!

**Comment by mindstorm38** [comment]
I think what's wrong with your example is that instead of "1.20.6-21.0.143", you should use the NeoForge versioning, using "20.6.120", you basically have to remove the first version number, but _not trivially_ have to find the patch number! Currently the launcher is using https://maven.neoforged.net/#/releases/net/neoforged/neoforge, you can always start a given Minecraft version, like "1.20.6", it should work.

**Comment by Trogiken** [comment]
I'm not sure if I 100% understand, but I think this is a non-issue in how you describe the solution. I'll make sure to close this then.

**Comment by mindstorm38** [comment]
> I'm not sure if I 100% understand, but I think this is a non-issue in how you describe the solution. I'll make sure to close this then.

This is not currently an issue strictly speaking, but I think that I'll improve this in the future when the NeoForge versioning will be more stable, I really don't understand their logic either.
