### ISSUE TITLE
start neoforge:1.20.4 and search neoforge versions

### ISSUE THREAD

**Issue by Scott-McKool** [mindstorm38/portablemc#233]
I want to launch neoforge version 1.20.4,
```
[joe@nixos:~]$ portablemc -vvv start neoforge:1.20.4
[ INFO ] Global version: neoforge 1.20.4 
[FAILED] Version neoforge-1.20.4-??? not found
```
i see in [the example in the README](https://github.com/mindstorm38/portablemc?tab=readme-ov-file#with-arch-linux)  `neoforge:1.20.1`, which works as expected.

i tried looking for valid versions using `portablemc search` but i see there is no option for searching neoforge.
```
[joe@nixos:~]$ portablemc -vvv search -k neoforge
usage: portablemc search [-h] [-k {mojang,local,forge,fabric,quilt,legacyfabric}] [input]
portablemc search: error: argument -k/--kind: invalid choice: 'neoforge' (choose from 'mojang', 'local', 'forge', 'fabric', 'quilt', 'legacyfabric')
```
is 1.20.4 an unsupported version? it appears on [the neoforge website](https://projects.neoforged.net/neoforged/neoforge). is there a reason why neoforge is absent from `portablemc search`? is there somewhere else i should look?

**Comment by mindstorm38** [comment]
Hello, thanks for the report, it's likely related to #228, I don't understand what's going on with their versioning and APIs but I've already fixed this twice in the past, so I'll take a look at how to support it. There is no search support for now because of this, the internal API about NeoForge is really unstable...

**Comment by mindstorm38** [comment]
Launching Neoforge 1.20.4 is working on my side...

**Comment by Scott-McKool** [comment]
my mistake, i thought i installed the latest version but in my package manager the latest version is still 4.3.0.

**Comment by mindstorm38** [comment]
Thanks! No problem.
