### ISSUE TITLE
Cant start the fabric

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#24]
Do I need somekind of special java or sth ?
![Capture](https://user-images.githubusercontent.com/59399625/126972900-9a9f1729-1df1-4f4f-8ea1-488594f8005c.PNG)

**Comment by mindstorm38** [comment]
Hi! Thank you for this report, this will be easier for me if you can add a bit of debug code into the script. Can you add `print(args)` after the line 719 (`ret = []` in function `interpret_args`) and try again, this will not fix the issue but ouput the arguments list, then you just share the output here.

**Comment by GoodDay360** [comment]
![image](https://user-images.githubusercontent.com/59399625/126979750-881eee6b-73fd-4df7-8164-e3d73d6d3d59.png)
![image](https://user-images.githubusercontent.com/59399625/126979802-4a82b0a0-2349-41ca-993b-23af5cef94b1.png)
I'm I putting it in the right line ? Seem to be the same error output.

**Comment by mindstorm38** [comment]
Thank you, this is the right line! I check this shortly

**Comment by GoodDay360** [comment]
Oh anyway after you done fix. Can you help me make a simple short launch script that launch minecraft fabric loader. (include offline mode too if possible). I know there a sample on the minecraft launcher lib but it give me error output almost(not all) like the one I had right now on your script. I guess I'm suppose to ask this in pull request but if I do it there you won't know what the error is.

**Comment by mindstorm38** [comment]
I don't understand how you managed to get this metadata format for arguments. To explain, when launching `fabric:1.16.5:0.11.6`, the fabric add-on download correct metadata to `.minecraft/versions/fabric-1.16.5-0.11.6`, this version depends on the `1.16.5` version. The problem seems to came from the version metadata `1.16.5` (at `.minecraft/versions/1.16.5/1.16.5.json`), this metadata were probably downloaded not by PortableMC, can you confirm that?

I know how to fix this issue, but before I need to know if the issue come from an old metadata format that I MUST support for retro-compatibility, or if this is an issue of another launcher.

Can you send here the metadata file for the version 1.16.5 ?

**Comment by GoodDay360** [comment]
@mindstorm38 Thank you for replying, I fixed the problem by delete version 1.16.5. If can, can you help me help me make a simple short launch script that launch minecraft fabric loader ?

**Comment by mindstorm38** [comment]
Have you checked the README? It describes all arguments to start the game. You can also use `start -h` sub command to get help for the start sub command.

Also, what type of script do you need, bash/python?

**Comment by GoodDay360** [comment]
@mindstorm38 I need a simple python script that start minecraft Fabric loader and load all the mobs. I was plaining to make a full GUI launcher for my Fabric server but I can't find a way to launch Fabric Loader. I tried learn your script but it's confusing.

**Comment by mindstorm38** [comment]
Ok, I'm assuming that you already have the script with the `modloader_fabric` add-on. Then you can start the launcher process using `subprocess` package in Python. You can use for example `start fabric:<minecraft_version> -u <username> -i <uuid>` to use offline mode profile. Argument `-i` is optional but can be useful in some cases.

**Comment by GoodDay360** [comment]
@mindstorm38 I dont understand which files you mean. I tried to launch command in powershell like this `python fabric.py start fabric:1.16.5 -u MCUser`. The out put seem to be none. It show nothing the powershell just open new line. But with `portablemc.py` it working fine. My goal is to make my python script convert into .exe so other people can easily install and launch my Minecraft launcher. But since there separate python file, if I use subprocess to launch the python script, other people also need to install python. So I'm just trying to make thing easy by making one script that contain the GUI+(way to launch minecraft fabric loader) inside one script. It's just that I been google for 2weeks I still can't find a way to launch Fabric loader. I was just expecting sample script like: 
```
mc_version = 1.16.5
loader_version = 0.11.6
# And then the code below will launch Fabric with Minecraft Version 1.16.5 with loader version 0.11.6
```
Thanks very much, for helping me.

**Comment by mindstorm38** [comment]
The `fabric.py` file will not launch, it is not made to be launched. As you said, only `portable.py` is working it load fabric add-on.

For bundling the python files in the `.exe` thing without requiring the user to download Python, I have never done this, so I can't help you. Maybe you can ship multiple files into the EXE, maybe not, I don't know :/

**Comment by GoodDay360** [comment]
@mindstorm38 Thanks.
