### ISSUE TITLE
Client Support

### ISSUE THREAD

**Issue by Kotsasmin** [mindstorm38/portablemc#25]
Can you play with a custom client like: Forge, Impact and so on? If you can't, I think it would be great if you could add it in the main project...

**Comment by mindstorm38** [comment]
Forge should work with PortableMC, if it is installed from the installer, you can start it. I will test on my installation, but I've already tested it previously, maybe the forge installation has slightly changed, and I need to adapt something.

If you can post more information below like the installation directory name of forge and its content (the content of the `.json` can be useful), and also the logs of the game when it has failed.

**Comment by Kotsasmin** [comment]
Forge is working (I tried 1.16.5 and 1.12.2) as long as you have the file: launcher_profiles.json in the same directory with the launcher. But a lot of custom clients (such as impact, badlion, lunar and so on) are not working well... I think it would be a great movement if you could make the launcher automatically scan and prints out all the installed minecraft versions and not only the vanilla versions (using -l)...

**Comment by Kotsasmin** [comment]
Anyway, you are one of the most active users in Github! I never show such a motivated user! Thanks a lot!
