### ISSUE TITLE
If any file download fails, the whole script ends.

### ISSUE THREAD

**Issue by ayunami2000** [mindstorm38/portablemc#27]
maybe it should have a handler that attempts download again?
command line used: `python3.9 portablemc.py start -u CollabVM`
(*this was not run on my own computer but on a virtual machine)
![image](https://user-images.githubusercontent.com/24785136/128616653-d9055581-df71-4d6a-943d-3f7b80af9e3c.png)

**Comment by mindstorm38** [comment]
I found the problem! Thanks for the help of making this launcher better and more stable, I hope that didn't prevent you from relaunching the download afterwards.

**Comment by ayunami2000** [comment]
I was able to just rerun it to resume downloading, but thank you for the
fix!

**Comment by mindstorm38** [comment]
New version 2.0.1 available with the fix!
