### ISSUE TITLE
Forge support

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#29]
It would be great if it can launch Forge

**Comment by GoodDay360** [comment]
Hey man, I got something for you: https://github.com/lordofwizard/mcserver/blob/main/JavaInstallScripts/ForgeInstall.
I found this script 2 months ago while I try to make a server on Google Cloud Shell. I just realized that in this script there is a link for you to get Forge_Version Id.
So just requests installer like this: `"https://maven.minecraftforge.net/net/minecraftforge/forge/{MCVER}-{FORGEVER}/forge-{MCVER}-{FORGEVER}-installer.jar"`

That's it! 😎

**Comment by GoodDay360** [comment]
Hey man, I got something for you: https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json.
I found this link a year ago while I try to make a server on Google Cloud Shell. I just realized that in this script there is a link for you to get Forge_Version Id.
So just requests installer like this: `"https://maven.minecraftforge.net/net/minecraftforge/forge/{MCVER}-{FORGEVER}/forge-{MCVER}-{FORGEVER}-installer.jar"`

That's it! 😎

**Comment by mindstorm38** [comment]
I've a complementary solution to this problem, I just found another interesting maven file.

**Comment by mindstorm38** [comment]
It's not that simple 😢 
Installer procedures have changed a lot of time in the past, and each of these installers doesn't provide a CLI argument to install the client (quite obvious regarding their choice of not allowing automation of the installation). To fix that, I need to make a small wrapper in Java which will hook itself into the installer and run the right code. And I will need one wrapper for each installation procedure.

**Comment by mindstorm38** [comment]
Update: I finished writing the wrapper, and it currently provides a unified interface to install forge up to Minecraft 1.6 (I haven't tested further). 🎉🎉

**Comment by mindstorm38** [comment]
Already working for latest versions, I've some issue launching 1.11 and older versions because of some syntax error in generated version metadata files and class not found exceptions.

**Comment by mindstorm38** [comment]
It's now possible to launch a version from 1.7.10 to 1.18.2! Some modifications were made to the launcher itself because it wasn't implementing rights algorithms for libraries resolution.

**Comment by mindstorm38** [comment]
First release of this addon is released today! Please test it and give me feedbacks in issues or discussions.

**Comment by Umatriz** [comment]
I'm also developing launcher in Rust. As I can see now you dont have any java wrappers. How do you installing it?
I'll be so grateful if you will explain how does it really works. Cause now I'm stuck with forge/neoforge installing.

**Comment by mindstorm38** [comment]
@Umatriz The forge installation is quite complicated, but I found over time that it's simpler to install it without actually running the Java installer. So in the current state, the launcher parses the JAR and acts depending on what found in it (because there is multiple version of the installer). Everything is implemented in https://github.com/mindstorm38/portablemc/blob/master/portablemc/forge.py

**Comment by Umatriz** [comment]
@mindstorm38 Big thanks!

**Comment by janekdeveloper** [comment]
@mindstorm38 Hi, I'm developing my own launcher. And I want to run forge versions. Can you please help me with this?
