### ISSUE TITLE
Auto close console when game launched

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#30]
Is there any way to auto close the console when the game is launched?

**Comment by GoodDay360** [comment]
Anyway how abt Auto close console when the game launched? can u do it?

**Comment by mindstorm38** [comment]
I will try today but this looks impossible since the Minecraft process is a child of the launcher, if the parent is killed the Minecraft process might be killed, anyway let's see.

**Comment by GoodDay360** [comment]
@mindstorm38 No it won't. If the launcher closed Minecraft won't close. Except if u run it in IDE. I use cmd to run PMC when I close the launcher it didn't close Minecraft.

**Comment by mindstorm38** [comment]
Have you tried with something like this?
```py

import subprocess

class LauncherRunnable(QRunnable):

    def __init__(self):
        super().__init__()

    def run(self):
        subprocess.run(<args>)

QThreadPool.globalInstance().start(LauncherRunnable())

```

**Comment by GoodDay360** [comment]
The threading process for the launcher is working fine. But the problem is that when the user launches the game more than one time which it's leads to console spam. But it's alright I will try my best to add it into your source code myself, thanks.
