### ISSUE TITLE
Microsoft auth not working

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#31]
Microsoft auth ain't open any webpage.

**Comment by mindstorm38** [comment]
On the latest version? Have you more details like OS, your web browser or anything printed in the terminal?

**Comment by GoodDay360** [comment]
@mindstorm38 latest version prints nothing it does nothing it launches the game with a random name.

**Comment by mindstorm38** [comment]
What is the command line?

**Comment by GoodDay360** [comment]
'start fabric:1.17.1 -m'

**Comment by mindstorm38** [comment]
Even for Microsoft auth, you need the `-l` (`--login`) argument with your mail, for now it's required because I'm unable to get a reliable documentation about their auth service. I will add a message to warn the user if the `-m` argument is used without `-l` and improve documentation.

**Comment by GoodDay360** [comment]
Anyway, can you make it close the PMC console after Minecraft loaded first in the next update? Cuz, There really a bad issue with my launcher when it does not close the PMC after Minecraft loaded.  Thanks, so much❤.

**Comment by mindstorm38** [comment]
I will do that later today 😉

**Comment by mindstorm38** [comment]
Argh, it's more complicated than I thought! In fact, I could just run it detached, but the problem is that I should delete the binaries' directory when Minecraft process exit!

**Comment by mindstorm38** [comment]
Switching to #30
