### ISSUE TITLE
--jvm-args not working

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#32]
My commands line
```pmc.exe start fabric:1.17.1 --jvm-args -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M```
![image](https://user-images.githubusercontent.com/59399625/131777496-f84ff144-4606-4ab1-b245-a69e3bea4c3b.png)

**Comment by GoodDay360** [comment]
You should check Miscellaneous agains. Some args ain't working.

**Comment by mindstorm38** [comment]
Ok I will check that
