### ISSUE TITLE
Can I write an introduction post for this project on MCBBS?

### ISSUE THREAD

**Issue by SNWCreations** [mindstorm38/portablemc#37]
This project is very cool! I like it very much. I hope to let more people know this project.
So I want to write an introduction post for this project on mcbbs (a Minecraft forum in China).
I will introduce the usage, installation method and more of this project.
Of course, I will add a link to this project and indicate the author.

Thanks!

@mindstorm38

**Comment by mindstorm38** [comment]
Hi, thank you for supporting this project! A post about portablemc is really welcome, do not hesitate to post the link here :)
