### ISSUE TITLE
Demande d'intégration

### ISSUE THREAD

**Issue by SyFizz** [mindstorm38/portablemc#4]
Bonjour,

J'ai développé une petite interface graphique en Python avec tkinter pour utiliser votre launcher, et je voudrais savoir si il y avait moyen de lancer le jeu via votre launcher sans garder la fênetre console ouverte, et si ce n'est pas le cas, ce serait une bonne amélioration à penser pour la prochaine version 😉 

Pour l'instant, je lance le launcher avec un `os.system('start ./bin/portablemc.py -u '+getInGameName()+' -v '+getSelectedVersion() + ' --main-dir ./data --jvm ./bin/bin/java.exe')`, mais c'est pas très joli de devoir garder la fenêtre ouverte en arrière-plan :(

Je précise que l'interface graphique est pour une utilisation dans un projet scolaire ^^

Cordialement,
SyFizz_

**Comment by mindstorm38** [comment]
Il me semble d'avec tkinter, ou plus généralement les application "windowed" (fenétrées), il faut explicitement dire à l'interpréteur python de ne pas lancer la console.

Sinon je pense que [cette réponse stackoverflow](https://stackoverflow.com/a/764654/7290330) peut vous intéresser (cela dépend de l'OS utilisé).

**Comment by SyFizz** [comment]
En soi, c'est pas tant mon GUI tkinter le problème, c'est la fênetre de logs du jeu...

Même en lançant lançant le launcher avec pythonw, effectivement les logs spécifiques au laucher ne s'affichent pas, mais à l'ouverture du jeu j'ai une fênetre `java.exe` qui m'affiche les logs :(

Je pense qu'il faudrait trouver comment le launcher officiel les met dans un fichier plutôt que dans une fênetre qui reste ouverte

P.S : En plus de m'intéresser au projet, j'habite aux alentours de grenoble aussi :p
Et pour info, le projet scolaire sur lequel j'utilise votre projet se passe au lycée Portes de L'Oisans, à Vizille

**Comment by mindstorm38** [comment]
Quel OS? C'est pour savoir car la fonction os.system ne régis pas pareil suivant les systèmes

**Comment by SyFizz** [comment]
Sous Windows 10 :)

**Comment by mindstorm38** [comment]
Je pense avoir trouvé, un détail m'avait échappé! Vous utilisez la commande "start" pour lancer le script, le problème de cette commande est qu'elle ouvre systématiquement l'application qui peut lancer le programme donné (donc le shell python ici, même si c'est dans un invite de commande). Du coup il faudrait plutôt utiliser l'executable python à la place de "start" (récupérable avec `sys.executable`).

PS: Sur les dernières versions de python il est conseillé d'utiliser le module `subprocess` à la place de `os.system`, ou au moins la fonction [`subprocess.run`](https://docs.python.org/fr/3/library/subprocess.html#subprocess.run).

**Comment by SyFizz** [comment]
Donc si je fais `os.system(sys.executable() './bin/portablemc.py -u '+getInGameName()+' -v '+getSelectedVersion() + ' --main-dir ./data --jvm ./bin/bin/java.exe')`, c'est censé fonctionner ? Si oui, ça ne fonctionne pas, j'ai juste plus rien qui apparaît :(

**Comment by mindstorm38** [comment]
Dans l'idée c'est ça! Cependant je conseillerais de l'écrire en une seule chaine de formattage, par exemple:
```py
os.system("{} ./bin/portablemc.py -u {} -v {} --main-dir ./data --jvm ./bin/bin/java.exe".format(sys.executable(), getInGameName(), getSelectedVersion()))
```
Le but est d'éviter les petite erreur comme l'espace, ou le '+' manquant après `sys.executable()`, ça donne une meilleur idée du résultat final.

**Comment by SyFizz** [comment]
Désolé, je suis un peu nul en python, mon truc c'est le java 🙁
Je teste ça de suite ^^

**Comment by mindstorm38** [comment]
Ahhhhhhh désolé xD `sys.executable` est une chaine, pas un fonction!

**Comment by SyFizz** [comment]
Okay, je tente ça de suite, j'édite ensuite :)

**Comment by mindstorm38** [comment]
C'est tout de même très bizarre, car en testant sur mon PC j'avais le pb (merci windows xD)!

**Comment by SyFizz** [comment]
Ahah, désolé pour le faux espoir, mais cacher la console n'était pas ma seule requête :p

Du coup, je voudrais savoir si lors du téléchargement des fichiers du jeu, il y a moyen de récupérer le "xx.xx% of total" pour en faire une barre de progression tkinter ?

Si vous préférez, on peut passer sur Discord afin d'éviter de flooder les issues sur le repo x)

**Comment by mindstorm38** [comment]
=> Mindstorm38#8760

**Comment by SyFizz** [comment]
Ajouté :)
