### ISSUE TITLE
offline UUID support

### ISSUE THREAD

**Issue by Kotsasmin** [mindstorm38/portablemc#40]
Is this possible? Non-legitimate players can set an UUID player skin??? Or no????

**Comment by Kotsasmin** [comment]
Neverming... I was wrong... You can use a custom uuid.... I am sorry...

**Comment by mindstorm38** [comment]
No problem! In modern versions the UUID is used to set the player's skin, so yes if you change the UUID you can grab someone' skin just by using its UUID (in offline mode obviously).
@Kotsasmin
