### ISSUE TITLE
LWJGL latest version and ARM support

### ISSUE THREAD

**Issue by GooseDeveloper** [mindstorm38/portablemc#62]
**SYSTEM INFORMATION**
Applicable `neofetch(1)` output:
```
OS: Manjaro ARM Linux aarch64 
Host: Raspberry Pi 400 Rev 1.0 
Kernel: 5.10.83-1-MANJARO-ARM-RPI 
Packages: 425 (pacman) 
Shell: bash 5.1.12
```

**SOFTWARE VERSIONS**
* `portablemc v2.2.2`
* `openjdk version "1.8.0_292"`
* Python 3.9.9

**EXPECTED RESULT**
* Functioning Minecraft client, `1.8.9`
* Full add-on support

**ACTUAL RESULT**
Output of `portablemc start 1.8.9 --jvm java` (username excluded):
```
[  OK  ] Resolved version 1.8.9.    
[  OK  ] Loaded version JAR.    
[  OK  ] Checked 734 assets.
[  OK  ] Loaded pretty logger.
[  OK  ] Loaded 33 libraries. 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (cppInterpreter_zero.cpp:835), pid=65814, tid=0x0000ffff9a487150
#  Error: Unimplemented()
#
# JRE version:  (8.0_292-b10) (build )
# Java VM: OpenJDK 64-Bit Zero VM (25.292-b10 interpreted mode linux-aarch64 )
# Core dump written. Default location: /home/goose/.minecraft/core or core.65814
#
# An error report file with more information is saved as:
# /home/goose/.minecraft/hs_err_pid65814.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**STEPS TO REPRODUCE**
* Start Arch Linux
* Install `portablemc`
* Execute `portablemc start --jvm`

**NOTES**
* PortableMC initially complains about a "Missing JVM," which I've worked around using `--jvm`

Thanks for reviewing!
[hs_err_pid1139.log](https://github.com/mindstorm38/portablemc/files/7866644/hs_err_pid1139.log)

**Comment by Ristovski** [comment]
What I think is happening here is that the manifest for Minecraft version `1.8.9` ships a version of lwjgl that is older than 3.2.3, which is the version that has `arm64` support.

@mindstorm38 Seems like having an option to override the used lwjgl version is useful after all :P

**Comment by GooseDeveloper** [comment]
> What I **think** (hard to tell without logs) is happening here is that the manifest for Minecraft version `1.8.9` ships a version of lwjgl that is older than 3.2.3, which is the version that introduces `arm64` support.
> 
> @mindstorm38 Seems like having an option to override the used lwjgl version is useful after all :P
> 
> Update: Here is the manifest for `1.8.9`: https://launchermeta.mojang.com/v1/packages/d546f1707a3f2b7d034eece5ea2e311eda875787/1.8.9.json
> 
> The lwjgl version used in that is `2.9.4`, which only contains x86_64 native libraries - https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
> 
> For `glfw3`, there could be an override allowing the use of whatever version is installed on the system. However, I don't think `lwjgl-2.x.x` (in the case of Minecraft 1.8.9) would work with `glfw3` (as opposed to `glfw2`). So there would still be no mechanism allowing the use of fully custom LWJGL versions.

I have edited the issue, including a log file (PID won't match as I re-ran the command)

**Comment by Ristovski** [comment]
> The issues persists in 1.18 with similar output

Indeed, it appears Mojang simply does not support anything other than x86, even though it should be fairly trivial - I believe you just need the native LWJGL libraries for the correct architecture.

Grabbing the LWJGL3 ones should be easy (even programmatically) - it even comes with a page to generate a customized "build" with only the required components - https://www.lwjgl.org/customize.

Figuring out how to get this working in a user-friendly manner is a different problem though.

LWJGL2 (needed for older versions) sadly does not have this, and would need to be compiled from source for each architecture.

I will look into this over the weekend and see if I can come up with anything.

**Comment by GooseDeveloper** [comment]
> > The issues persists in 1.18 with similar output
> 
> Indeed, it appears Mojang simply does not support anything other than x86, even though it should be fairly trivial - I believe you just need the native LWJGL libraries for the correct architecture.
> 
> Grabbing the LWJGL3 ones should be easy (even programmatically) - it even comes with a page to generate a customized "build" with only the required components - https://www.lwjgl.org/customize.
> 
> Figuring out how to get this working in a user-friendly manner is a different problem though.
> 
> LWJGL2 (needed for older versions) sadly does not have this, and would need to be compiled from source for each architecture.
> 
> I will look into this over the weekend and see if I can come up with anything.

Thanks. Will I need to change anything inside the game directory, or does updating LWGL suffice?

**Comment by GooseDeveloper** [comment]
> > The issues persists in 1.18 with similar output
> 
> Indeed, it appears Mojang simply does not support anything other than x86, even though it should be fairly trivial - I believe you just need the native LWJGL libraries for the correct architecture.
> 
> Grabbing the LWJGL3 ones should be easy (even programmatically) - it even comes with a page to generate a customized "build" with only the required components - https://www.lwjgl.org/customize.
> 
> Figuring out how to get this working in a user-friendly manner is a different problem though.
> 
> LWJGL2 (needed for older versions) sadly does not have this, and would need to be compiled from source for each architecture.
> 
> I will look into this over the weekend and see if I can come up with anything.

I installed lwjgl from [the aur](https://aur.archlinux.org/packages/lwjgl), but I receive the same error

**Comment by mindstorm38** [comment]
Thank you, @GooseDeveloper, for reporting this issue, and thank you, @Ristovski, for answering :)

As Ristovski, the issue does not come from the launcher, Mojang implicitly provides "native" JAR files only for x86 architectures. No fix for this is currently implemented in the launcher.

> I installed lwjgl from the aur, but I receive the same error
What do you mean by installing from AUR? I know AUR is a dependency manager with community packages, but where is it installed? In Maven local repository? 

Anyway, it's not currently supported to manually modify the JAR file in `libraries` directory in `.minecraft`, the launcher will keep checking its integrity and will re-download it.

Because I think that's important to be able to run Minecraft from my launcher on ARM, I will on a fix that will be automatically applied to version's metadata.

**Comment by mindstorm38** [comment]
Could you send us the output of:
```py
import platform
platform.system()
platform.machine()
platform.architecture()
```

**Comment by mindstorm38** [comment]
There is also an issue with `text2speech` which is a Mojang library, and uses a `libfliteWrapper` shared object.

**Comment by mindstorm38** [comment]
The crash log says that VM is not fully initialized when it crashed. I think it doesn't come from native libraries, at least in the first time. I will try it on a RPi 400, I have to see it from my own eyes 🧐

**Comment by Ristovski** [comment]
> There is also an issue with `text2speech` which is a Mojang library, and uses a `libfliteWrapper` shared object.

This one is non-fatal and it simply causes the text2speech module to not initialize afaik

**Comment by GooseDeveloper** [comment]
> The crash log says that VM is not fully initialized when it crashed. I think it doesn't come from native libraries, at least in the first time. I will try it on a RPi 400, I have to see it from my own eyes monocle_face

If you don't already own a Raspberry Pi 400, I'd use a VM or Raspberry Pi 4

**Comment by GooseDeveloper** [comment]
> Could you send us the output of:
> 
> ```python
> import platform
> platform.system()
> platform.machine()
> platform.architecture()
> ```

Here you go:
```python
'Linux'
'aarch64'
('64bit', 'ELF')
```

**Comment by mindstorm38** [comment]
Thank you! Also, I own a RPi 400, so I can test it directly on it

**Comment by mindstorm38** [comment]
The (expected) error that I get on my system, running Minecraft 1.8.9 (with a OpenJDK 11.0.12 JVM) is `java.lang.UnsatisfiedLinkError: /home/pi/.minecraft/bin/[...]/liblwjgl.so: [...] (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)`.

Your crash seems to happen very early in loading process, could you try with OpenJDK 11 for example?

**Comment by mindstorm38** [comment]
Minecraft 1.18.1 is using LWJGL 3.2.2, this is the latest version that doesn't support ARM. Version 3.2.3 supports Linux ARM 64/32 and windows natives are split between x64/x86 (was previously merge into one JAR). Version 3.3.0 introduce ARM64 for macOS and Windows.

I don't know if these versions are supported by Minecraft, but I will test them anyway because it seems to be the only way to run Minecraft on ARM.

**Comment by mindstorm38** [comment]
It's really hard to know what to do, modifying the version metadata will invalidate it, so it will be re-downloaded each time (I hope Mojang will officially support ARM). The best solution for now is to modify metadata once loaded, just before calling `Version.prepare_libraries`.

**Comment by GooseDeveloper** [comment]
Thanks! Sorry I was gone... I didn't realize this was an ARM problem, rather than a Minecraft problem. Is there any dependencies I should know about, specifically mutually exclusive (JDK 8 vs JDK 17)?

**Comment by mindstorm38** [comment]
I don't know dependencies that would be useful in that case. From what I see, and I can be wrong, it seems to be an issue when starting the JVM itself, before actually loading Minecraft. I tested on the same hardware (but not the same distro) a modern JVM and it worked, because Minecraft was in my case trying to load the shared libraries, which is not the case in your crash report.

**Comment by mindstorm38** [comment]
It's promising! :)

**Comment by mindstorm38** [comment]
![mc_on_rpi400](https://user-images.githubusercontent.com/17071361/150639952-c4854dda-cb5b-4144-9e54-ec8b4de113ef.png)

LWJGL 3.2.3 works! Bu 3.3.0 have an issue with GLFW error callback, I'll report this issue to LWJGL maintainers because it doesn't seems to came from MC itself.

**Comment by mindstorm38** [comment]
https://github.com/LWJGL/lwjgl3/issues/720

**Comment by GooseDeveloper** [comment]
I'm installing LWJGL 3.2 now... Will PortableMC 2.2.3 `feature/arm-support` work?

**Comment by mindstorm38** [comment]
If you want to test, the up-to-date branch is `feature/lwjgl-version-arg`. I need some feedback before releasing 2.2.3 (and would like to receive an answer from lwjgl devs about the issue with 3.3.0).

**Comment by GooseDeveloper** [comment]
I'm getting support in LWJGL, then I'll try the following:
- LWJGL 3.2.3
- PortableMC 2.2.2
- Java 17 via OpenJDK
Will these work?

P.S. Thank you so much for all these pages and an entire branch for one GH issue :+1:

**Comment by GooseDeveloper** [comment]
I changed to Java version 17 via OpenJDK and got this error instead:
```
[11:33:41] [main/WARN]: Unrecognized user type: 
[11:33:41] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[11:33:41] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[11:33:41] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "Render thread" [11:33:41] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[11:33:41] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:65)
[11:33:41] [Render thread/INFO]: [STDERR]: 	at dxo.a(SourceFile:2420)
[11:33:41] [Render thread/INFO]: [STDERR]: 	at dxo.a(SourceFile:2415)
[11:33:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:208)
```

**Comment by mindstorm38** [comment]
Hmmm I checked and this should work, could you give me the list of file in the directory created in the `.minecraft/bin` directory? I've already fixed this issue in a previous commit, so I'm a bit surprised.

**Comment by mindstorm38** [comment]
Here is a copy of the latest version in a single file.
[portablemc-single-2.2.3-preview.1.zip](https://github.com/mindstorm38/portablemc/files/7944260/portablemc-single-2.2.3-preview.1.zip)

**Comment by GooseDeveloper** [comment]
For some reason, `~/.minecraft/bin` is empty and running `portablemc.py` from the archive produces the same error. I tried removing `~/.minecraft` and restarting Minecraft, but the same error occurred.

(I'd be happy to become a contributor)

**Comment by GooseDeveloper** [comment]
FYI, `~/.minecraft/libraries/org/lwjgl/lwjgl` contains a directory called `3.2.2`, which I assume to be the LWJGL version currently installed. Maybe this is the issue?

**Comment by mindstorm38** [comment]
Have you tried to check the content of bin after starting but before the game is crashing ? Because files are only existing while the game is running.

For lwjgl version 3.2.2 existing in libraries it's expected and should not cause any issue.

**Comment by GooseDeveloper** [comment]
Files in `~/.minecraft/bin/$uuid`: ```
libfliteWrapper.so
libglfw.so
libglfw_wayland.so
libjemalloc.so
liblwjgl.so
liblwjgl_opengl.so
liblwjgl_stb.so
liblwjgl_tinyfd.so
libopenal.so
```

**Comment by mindstorm38** [comment]
Which Minecraft version btw?

**Comment by mindstorm38** [comment]
Hmm anyway it should not cause this kind of problem, an interesting thing you can do is to add the `"--jvm-args=-Dorg.lwjgl.util.DebugLoader=true"` argument to the start command. It will produce a better output for this type of issue.

**Comment by GooseDeveloper** [comment]
I'm starting Minecraft 1.18.1 with PortableMC 2.2.2. Here's some output:

    % portablemc start 1.18.1 --jvm java --jvm-args=-Dorg.lwjgl.util.DebugLoader=true
    [11:19:55] [main/WARN]: Unrecognized user type: 
    [11:19:56] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
    	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
    	b) Add the JAR that contains the shared library to the classpath.
    [11:19:56] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
    Exception in thread "Render thread" [11:19:56] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
    [11:19:56] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:65)
    [11:19:56] [Render thread/INFO]: [STDERR]: 	at dxo.a(SourceFile:2420)
    [11:19:56] [Render thread/INFO]: [STDERR]: 	at dxo.a(SourceFile:2415)
    [11:19:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:208)
968

Install command:

    pip install git+https://github.com/mindstorm38/portablemc@feature/lwjgl-version-arg

**Comment by mindstorm38** [comment]
Ok, so it crashes if you omit `--lwjgl ...` argument?

**Comment by mindstorm38** [comment]
If it works for you, I will release 2.3.0 asap :)

**Comment by GooseDeveloper** [comment]
> 

Thanks =)

I'll try it with the `--lwjgl` argument as soon as I can; fingers crossed

**Comment by GooseDeveloper** [comment]
> Ok, so it crashes if you omit `--lwjgl ...` argument?
> 
> If you are on ARM, it's expected to get this error if you dont specify the lwjgl argument, if you want to run it on ARM, using `--lwjgl 3.2.3` argument should works fine!

I'll try it with `--lwjgl` as soon as I can... Fingers crossed =)

**Comment by mindstorm38** [comment]
What do you think about this being manual? I thought it could be confusing if this argument was implicitly set when on ARM devices, because it modifies the version's metadata, and it could break in the future, I don't want it to be an "unplanned obsolescence".

**Comment by GooseDeveloper** [comment]
Maybe add a `~/.minecraft/defaults.txt` containing flags to be used by default. Then, bug fixes like this could use a simple patch:

    jvm java
    lwjgl 3.2.3

**Comment by GooseDeveloper** [comment]
> Ok, so it crashes if you omit `--lwjgl ...` argument?
> 
> If you are on ARM, it's expected to get this error if you dont specify the lwjgl argument, if you want to run it on ARM, using `--lwjgl 3.2.3` argument should works fine!

The `--lwjgl` argument isn't recognized by PortableMC. Install command:

    pip install --user git+https://github.com/mindstorm38/portablemc@feature/lwjgl-version-arg

**Comment by mindstorm38** [comment]
You don't get it when doing `start --help`? You are probably have the wrong version installed, maybe using `--upgrade --force-reinstall` when installing with pip could fix that? 

For the defaults' arguments file, I initially designed the launcher to be used with terminal aliases instead of environment variables or configuration file.

**Comment by GooseDeveloper** [comment]
Progress! Running `portablemc start --jvm java --lwjgl 3.2.3` makes it to GLFW, but crashes with error 65543 (GLXBadFBConfig)

**Comment by GooseDeveloper** [comment]
Also, I get a warning for "Unrecognized User Type" that might pose an issue later

**Comment by mindstorm38** [comment]
Ohhhh right! I missed this, but I effectively used this parameter on my first screenshot! I will note this on the README. Thank you for the support, I'll release the new version tomorrow, and credit you :)

**Comment by theofficialgman** [comment]
Hi you are welcome to use my replacement minecraft metadata server for ARMhf and ARM64 linux.
It automatically updates and includes ARMhf and ARM64 support for every minecraft version on Linux.
You simply replace mojangs metadata server with mine and thats it. No launcher changes necessary typically. Currently used in GDLauncher for a year or two now. The binaries used were compiled by myself (or official lwjgl builds when available) and are also used officially by Prism Launcher.

Refer to the readme at the repos for further explanation.
https://github.com/theofficialgman/piston-meta-arm64
https://github.com/theofficialgman/piston-meta-arm32
