### ISSUE TITLE
Make forge addon support mods in global folder. (/.minecraft/mods)

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#63]
I know I had asked you to make it use mods inside version folders but it would be amazing if you can make it also support the global mods folder.

**Comment by GoodDay360** [comment]
oh nvm, I thought it use mods inside the versions folder. But anyways I hope both options available

**Comment by mindstorm38** [comment]
Are you talking about forge addon or modrinth? The forge addon doesn't interact with mods folder

**Comment by GoodDay360** [comment]
forge. You know load mods inside of `versions/fabric-1.8.9` folder

**Comment by mindstorm38** [comment]
I didn't know that was possible, forge isn't managing this?

**Comment by mindstorm38** [comment]
Or are you suggesting implementing this manually?

**Comment by mindstorm38** [comment]
One month from the latest release, I need to release a new one this month at least, could we re-open this issue? @GoodDay360
