### ISSUE TITLE
Forge failed to install for lower versions

### ISSUE THREAD

**Issue by GoodDay360** [mindstorm38/portablemc#64]
Forge addon fails to install when on lower versions maybe version > 1.16.5 ( Like 1.8.9). From what I knew it might be a Java problem. Since the newer version needs Java16 but in the older version, it may need Java8 to install the forge installer.

**Comment by GoodDay360** [comment]
![image](https://user-images.githubusercontent.com/59399625/151661787-961584d5-615e-4c7c-b1d3-228684813131.png)
It also error when using custom -jvm path

**Comment by GoodDay360** [comment]
Forgot the installer error I managed to fix it. ofc it the different PC different java setup issue again.

**Comment by Ristovski** [comment]
> Forgot the installer error I managed to fix it. ofc it the different PC different java setup issue again.

Could you expand on this? If you managed to fix it, what was the issue? And what do you mean by "different java setup issue again"?

**Comment by mindstorm38** [comment]
The path given to `--jvm` must the one to the jvm executable

**Comment by mindstorm38** [comment]
Is it solved?

**Comment by GooseDeveloper** [comment]
In issue #62, I had a problem with 1.18 and LWJGL. However, the initial issue has recurred with `forge:1.8.9`

**Comment by GoodDay360** [comment]
Okeh here is what I did to solve I use Java8 to install versions lower than 1.14.4. Java16 for 1.14.4 or higher.

**Comment by mindstorm38** [comment]
Ok, it's actually an issue with the forge add-on, it is currently launching the wrapper using the `java` command, I will change this to use the auto-installed JVM, or the `--jvm` argument if present. This will be much easier to use, it's an error I shouldn't have done in the first place :/

**Comment by mindstorm38** [comment]
Updated forge add-on to v1.0.1 (I don't know if I'm going to release a patch version for the whole launcher, because no mod were made in it).
