### ISSUE TITLE
cant login to ms account (solved)

### ISSUE THREAD

**Issue by LifeTecLover999** [mindstorm38/portablemc#66]
im just getting this warning when I used the -m argument:
`Even if you are using -m (`--microsoft`), you must use `-l` argument with your Microsoft email.`

idk why

EDIT: i just used the wrong launch args I used start instead of login lol

**Comment by mindstorm38** [comment]
If you want to start the game with your Microsoft session, you can use the `-l <email>` argument together with the `-m` flag if your account has been migrated to MS.
