### ISSUE TITLE
type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by ayunami2000** [mindstorm38/portablemc#70]
**Describe the bug**
type object 'datetime.datetime' has no attribute 'fromisoformat'

**To Reproduce**
PortableMC version: current latest
Python version: 3.6 (this is important!)
Add-ons: 1.12.2
use PYTHON3.6 and run it a 2nd time after having run it once initially.

**Expected behavior**
it launches again

**Screenshots**
not necessary

**Additional context**
[type object 'datetime.datetime' has no attribute 'fromisoformat'](https://stackoverflow.com/questions/60266554/type-object-datetime-datetime-has-no-attribute-fromisoformat) see this link and it says python3.6 doesnt support this so ur gonna wanna like polyfill it or something

**Comment by mindstorm38** [comment]
Thank you for your preparatory work! I will fix that in the next patch release.

**Comment by mindstorm38** [comment]
Thank you, implemented in latest release 2.3.1
