### ISSUE TITLE
[Quilt Modloader] New Mod loader

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [mindstorm38/portablemc#74]
Heya, could [Quilt](https://quiltmc.org/) be added as a modloader addon? It's a hard-fork of Fabric and has already gained a lot of traction currently, so would be useful!

**Comment by mindstorm38** [comment]
Good idea! I never used it, but it might be a good opportunity to try it

**Comment by mindstorm38** [comment]
The API is quite similar to the fabric's one. Maybe it's simpler to just add Quilt support to the already existing Fabric add-on, it would be simpler, but not providing a "quilt" add-on might be confusing for users.
