### ISSUE TITLE
Multiline and scrollable console

### ISSUE THREAD

**Issue by rayzchen** [mindstorm38/portablemc#89]
When using portablemc-console, the end of some lines are cut off, like this:
![image](https://user-images.githubusercontent.com/54078384/180600115-6871af08-eff3-4987-9c0d-7721fac8a7c0.png)
Also, can you make the console scrollable so earlier entries can be seen?

**Comment by mindstorm38** [comment]
A cursor should be active on the console window, you can move it with arrow keys as usual. You can then move to lines you are interested in and move the cursor to the end of line.

**Comment by rayzchen** [comment]
Ah, I missed that. Thanks!

**Comment by mindstorm38** [comment]
Tell me if the buffer is too short, I might add an argument later to increase it..

**Comment by rayzchen** [comment]
Could you add an option to turn on line wrapping?

**Comment by mindstorm38** [comment]
I think it's possible, I will look into it
