### ISSUE TITLE
Missing License?

### ISSUE THREAD

**Issue by kz-n** [mindstorm38/portablemc#9]
I would like to use this in my project, is the licensefile missing from this repo or are all the rights reserved?

**Comment by mindstorm38** [comment]
You are right! I will add a license, but note that rights are not reserved, and I will put a free software license.

**Comment by kz-n** [comment]
That's good to know

**Comment by mindstorm38** [comment]
Done!

**Comment by mindstorm38** [comment]
I reopen this issue because I will need to add the license header to the script, but for now I keep it like this.

**Comment by mindstorm38** [comment]
Fixed in the [latest pre-release](https://github.com/mindstorm38/portablemc/releases/tag/v1.1.4-pre1).
