### ISSUE TITLE
Command line option to output log to file

### ISSUE THREAD

**Issue by rayzchen** [mindstorm38/portablemc#96]
It's too hard to try and copy paste the log from the console

**Comment by mindstorm38** [comment]
I understand what do you mean, the game's latest log file is by default created by the game itself. Maybe I can print its path in the console? Or are you referring to something else?

**Comment by rayzchen** [comment]
Ah, I didn’t realize the game saved its own log file.

**Comment by mindstorm38** [comment]
No problem! The idea of outputting the log's path is not that bad...

**Comment by mindstorm38** [comment]
Finally, I decided not to implement this in near future, because this requires inspection of log configurations (XML) to know exactly how the latest log path is saved.
