### ISSUE TITLE
Add examples for more arguments

### ISSUE THREAD

**Issue by miapuffia** [mindstorm38/portablemc#97]
I'm trying to use the --resolv and --no-better-logging arguments but I can't seem to get it to work. The full command I'm using without those is:

```
portablemc
--main-dir "C:\Users\%USERNAME%\curseforge\minecraft\Install"
--work-dir "C:\Users\%USERNAME%\curseforge\minecraft\Instances\MC Eternal"
start "--jvm-args=-Xmx16G -Xms16G -Xmn768m -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:-UsePerfData -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=50 -XX:G1HeapRegionSize=1 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US"
%install_name%
```

Where in that can I put those two flags?
Thanks

**Comment by mindstorm38** [comment]
These arguments should work fine if placed just before `%install_name%`, except `--resolv` is written `--resol <width>x<height>` (I hope it's just a typo, if not, please correct me).

**Comment by miapuffia** [comment]
I tried with --resol and it still appears to have no effect. Full command:

```
portablemc
--main-dir "C:\Users\%USERNAME%\curseforge\minecraft\Install"
--work-dir "C:\Users\%USERNAME%\curseforge\minecraft\Instances\MC Eternal"
start "--jvm-args=-Xmx16G -Xms16G -Xmn768m -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:-UsePerfData -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=50 -XX:G1HeapRegionSize=1 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US"
--resol 2560x1440 --no-better-logging
%install_name%
```

**Comment by mindstorm38** [comment]
Ok now I've time to work on the issue... Have you any output logs that may show errors? If not, I advise you to install the `portablemc-console` addon as it will display a nice logs console. Typically, I tried the arguments you give and I got an error from the JVM `Unrecognized VM option 'AggressiveOpts'`.

**Comment by miapuffia** [comment]
Does portablemc-console also output to a file? I'm running with a ton of mods and the log is very long. If you only need the first section I can probably capture that before it dumps the rest.

**Comment by mindstorm38** [comment]
If the game actually output logs, it's fine and I'm interested in them. It's weird that the game successfully start but crash later, have you tried without options ? Does it work without them ? It might be an issue with the launcher itself and not options.

**Comment by miapuffia** [comment]
The game doesn't crash for me. It just doesn't respect the --resol argument. I've attached the log
[latest.log](https://github.com/mindstorm38/portablemc/files/9639254/latest.log)

**Comment by mindstorm38** [comment]
@miapuffia Which game version are you launching btw?

**Comment by miapuffia** [comment]
1.12.2 with forge-14.23.5.2854

**Comment by mindstorm38** [comment]
Okay, thank you, I'll try this tomorrow

**Comment by miapuffia** [comment]
For some more information, I'm using your script to bypass launching with the curseforge launcher. It's much more convenient and faster to start with one click instead of waiting for curseforge, waiting for the minecraft launcher, and only then starting.

**Comment by mindstorm38** [comment]
@miapuffia I fixed the issue with resolution for old versions! Now it works with 1.12 :)

**Comment by miapuffia** [comment]
Can confirm it's fixed. Thanks!
